### ISSUE TITLE
更新docker容器的基础环境

### ISSUE THREAD

**Issue by weimengxi** [g-bbfe/api-blueprint-docker#1]
@Jack-X-Yang 

# 需求

## 系统和基础工具
centos@6.x.x
epel-release 
nginx（你看着装好了）
git
oh-my-zsh

## 以下比较在意的实用工具
node@7.x.x
npm@5.x.x

#### global 的 npm 包
webpack@3.x.x
webpack-dev-server
gulp@4.x.x
aglio (api-blueprint的语法解析器，可以转换为html)
drakov ( 能识别api-blueprint语法的api mock server)

**Comment by Jack-X-Yang** [comment]
重写了docker file，centos@6.9，别的基本上都是装的最新的，我这边跑了一下，镜像构建没什么问题。
不知道api blue-print能不能跑起来。
